version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: agrofields
      POSTGRES_USER: agro
      POSTGRES_PASSWORD: agro_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgresql+psycopg2://agro:agro_pass@db:5432/agrofields
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  pgdata: 