version: '3.8'

services:
  db:
    image: kartoza/postgis:15-3.3
    environment:
      - POSTGRES_DB=agrofields
      - POSTGRES_USER=agro
      - POSTGRES_PASS=agro_pass
      - ALLOW_IP_RANGE=0.0.0.0/0
    volumes:
      - db_data:/var/lib/postgresql
    ports:
      - "5432:5432"

  web:
    build: .
    command: python app.py
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql+psycopg2://agro:agro_pass@db:5432/agrofields
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  db_data: 