version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-root
    restart: unless-stopped
    init: true
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - backend
    environment:
      DATABASE_URL: postgresql+psycopg2://agro:agropass@db:5432/agrofields

  db:
    image: kartoza/postgis:15-3.3
    container_name: db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=agrofields
      - POSTGRES_USER=agro
      - POSTGRES_PASS=agropass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U agro"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  pgdata: 