version: '3.8'

# Volumes #####################################################################
volumes:
  frost_db_data:
    # external: true
  dbbackups:
    # external: true
  pgadmin_data:


# Networks ####################################################################
networks:
  net:
    driver: bridge

services:
  frost_db:
    container_name: frost_db
    image: "kartoza/postgis:${FROST_DB_VERSION}"
    ports:
      - "5432:5432"
    networks:
      - net
    shm_size: '1gb'
    environment:
      POSTGRES_DB: ${FROST_DB_NAME}
      POSTGRES_USER: ${FROST_DB_USER}
      POSTGRES_PASSWORD: ${FROST_DB_PASSWORD}
      POSTGRES_GROUP_NAME: ${FROST_DB_GROUP_NAME}
      POSTGRES_MULTIPLE_EXTENSIONS: ${FROST_DB_EXTENSIONS}
      PGDATA: "/var/lib/postgresql/data/pgdata"
      PGUSER: ${FROST_DB_USER}
      REPLICATION: "false"
      IGNORE_INIT_HOOK_LOCKFILE: "false"
      PASSWORD_AUTHENTICATION: "md5"
      RUN_AS_ROOT: "true"
    volumes:
      - frost_db_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
      - ./zones_regions.gpkg:/docker-entrypoint-initdb.d/zones_regions.gpkg
    restart: on-failure
    healthcheck:
      test: "PGPASSWORD=${FROST_DB_PASSWORD:?FROST_DB_PASSWORD not set} pg_isready -h 127.0.0.1 -U ${FROST_DB_USER:?FROST_DB_USER not set} -d ${FROST_DB_NAME:?FROST_DB_NAME not set}"
      interval: 10s
      timeout: 5s
      retries: 5
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: ${PGADMIN_CONFIG_SERVER_MODE}
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: ${PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED}
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: ${PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION}
      PGADMIN_CONFIG_WTF_CSRF_CHECK_DEFAULT: ${PGADMIN_CONFIG_WTF_CSRF_CHECK_DEFAULT}
      PGADMIN_CONFIG_WTF_CSRF_ENABLED: ${PGADMIN_CONFIG_WTF_CSRF_ENABLED}
    ports:
      - "5050:80"
    networks:
      - net
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - frost_db
    entrypoint: /bin/sh -c "chmod 600 /pgpass; /entrypoint.sh;"
    user: root
    configs:
      - source: servers.json
        target: c/servers.json
      - source: pgpass
        target: /pgpass
    tty: true
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
         DATABASE_URL: postgresql+psycopg2://postgres:postgres@frost_db:5432/frostdb
    depends_on:
      - frost_db
    networks:
     - net
    restart: unless-stopped

configs:
  pgpass:
    content: frost_db:5432:*:${FROST_DB_USER:?FROST_DB_USER not set}:${FROST_DB_PASSWORD:?FROST_DB_PASSWORD not set}
  servers.json:
    content: |
      {"Servers": {"1": {
        "Group": "Servers",
        "Name": "My Local Postgres 16.1",
        "Host": "frost_db",
        "Port": 5432,
        "MaintenanceDB": "postgres",
        "Username": "${FROST_DB_USER:?FROST_DB_USER not set}",
        "PassFile": "/pgpass",
        "SSLMode": "prefer"
      }}}