version: '3.8'

services:
  db:
    image: kartoza/postgis:15-3.3
    environment:
      - POSTGRES_DB=agrofields
      - POSTGRES_USER=agro
      - POSTGRES_PASS=agropass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata: 